# Label name and color to set, when potential duplicates are detected
issueLabel: "Type: potential duplicate"
labelColor: D2DAE1

# If similarity is higher than this threshold, issue will be marked as duplicate
threshold: 0.60

# Comment to post when potential duplicates are detected
referenceComment: >
  Potential duplicates:
  {{#issues}}
    - [#{{ number }}] {{ title }} ({{ accuracy }}%)
  {{/issues}}